run_name: indo_pacific
output_directory: .
job_name: TALAUD_ISLANDS_INDONESIA_20240901_195925
generate_dataset: True
num_jobs: 20

seismic_context:
  components: 'ZEN'
  stations_path: './configs/indo_pacific/stations.txt'
  station_components_path: './configs/indo_pacific/components.json'
  seismogram_duration: 900
  sampling_rate: 1
  syngine_address: "/data/shared/prem_i_10s" # if no local version, can use "syngine://prem_i_2s"
  processing:
    filter:
      type: 'bandpass'
      freqmin: 0.02
      freqmax: 0.04
      corners: 4
      zerophase: False

parameters:
  inference:
    moment_tensor:
      #         [Mrr, Mt, Mpp, Mrt, Mrp, Mtp]
      fiducial: [1.e+15, 1.e+15, 1.e+15, 1.e+15, 1.e+15, 1.e+15]
      stencil_deltas: [1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10]
      bounds: [[-5.e+16, -5.e+16, -5.e+16, -5.e+16, -5.e+16, -5.e+16],
              [5.e+16, 5.e+16, 5.e+16, 5.e+16, 5.e+16, 5.e+16]]
  nuisance:
    source_location:
      #         [lat, long, depth, time]
      fiducial: [3.8194,  126.4897 , 25, 0]
      bounds: [3.8194,  126.4897, 25, 0]


simulations:
  num_simulations: 1000
  sampling_method: 
    moment_tensor: "uniform"
    source_location: "constant"
  use_fisher_to_constrain_bounds: 15


compression: 

  optimal_score:
    empirical_block:  '/data/alex/noise/indo_pacific/azores_event_samples'

inference:
  sbi:
    method: 'posterior'

    noise_model: 
      type: 'real_noise'
      noise_catalogue_path: '/data/alex/noise/indo_pacific/azores_event_samples'
      noise_level: 3.e-6

  likelihood: 
    run: True
    ensemble: False
    covariance: empirical
    num_samples: 10000
    walker_burn_in: 2000
    move_size: 0.0005


jobs:
  real_events: 
    real_north: /data/alex/indo_pacific/events/TALAUD_ISLANDS_INDONESIA_20240901_195925_Lat3.8194_Lon126.4897_event_filtered_1hz.h5
  simulations:
    random_events: 0
    fixed_events: []
    custom_events: {}
  noise_models:
    real_noise: '/data/alex/noise/indo_pacific/azores_event_samples'
  plots:
    async_plotting: True
    test_posteriors: 
      chain_consumer: 
        - [[optimal_score, real_noise], [gaussian_likelihood, real_noise]]
    disable_plotting: False
