run_name: indo_pacific
output_directory: .
job_name: PAPUA_NEW_GUINEA_20240908_231532
generate_dataset: True
num_jobs: 20

seismic_context:
  components: 'ZEN'
  stations_path: './configs/indo_pacific/stations.txt'
  station_components_path: './configs/indo_pacific/components.json'
  seismogram_duration: 1740
  sampling_rate: 0.5
  syngine_address: "/data/shared/prem_i_10s" # if no local version, can use "syngine://prem_i_2s"
  processing:
    filter:
      type: 'bandpass'
      freqmin: 0.01
      freqmax: 0.02
      corners: 4
      zerophase: False
    sampling_rate: 0.5

parameters:
  inference:
    moment_tensor:
      #         [Mrr, Mt, Mpp, Mrt, Mrp, Mtp]
      fiducial: [7.990e+14, 1.111e+15, 9.064e+14, -1.355e+15, 1.829e+15, -2.018e+14]
      stencil_deltas: [1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10, 1.e+10]
      bounds: [[-5.e+16, -5.e+16, -5.e+16, -5.e+16, -5.e+16, -5.e+16],
              [5.e+16, 5.e+16, 5.e+16, 5.e+16, 5.e+16, 5.e+16]]
    source_location:
      #         [lat, long, depth, time]
      fiducial: [ -4.1123, 142.9635, 40.4, -100]
      stencil_deltas: [0.0001, 0.0001, 0.01, 0.001]
      bounds: [[ -4.1123, 142.9635, 40.4, 0],
             [ -4.1123, 142.9635, 40.4, 0]]
  nuisance: {}
simulations:
  num_simulations: 1000
  sampling_method: 
    moment_tensor: "uniform"
    source_location: "uniform"
  use_fisher_to_constrain_bounds: 15
  iterative_least_squares:
    max_iterations: 20
    damping_factor: 0.01

compression: 

  optimal_score:
    empirical_block:  '/data/alex/noise/indo_pacific/long_period_samples'

inference:
  sbi:
    method: 'posterior'

    noise_model: 
      type: 'real_noise'
      noise_catalogue_path: '/data/alex/noise/indo_pacific/long_period_samples'
      noise_level: 3.e-6

  likelihood: 
    run: False
    ensemble: False
    covariance: empirical
    num_samples: 10000
    walker_burn_in: 2000
    move_size: 0.0005


jobs:
  real_events: 
    papau_free_shifted: /data/alex/indo_pacific/events_0.5hz/NEW_GUINEA_PAPUA_NEW_GUINEA_20240908_231532_Lat-4.1123_Lon142.9635_event_filtered_0.5hz.h5
  simulations:
    random_events: 0
    fixed_events: []
    custom_events: {}
  noise_models:
    real_noise: '/data/alex/noise/indo_pacific/long_period_samples'
  plots:
    async_plotting: True
    test_posteriors: 
      chain_consumer: 
        - [[optimal_score, real_noise], [gaussian_likelihood, real_noise]]
    disable_plotting: False
