import numpy as np

def create_ipma_data_format(data_path):
    civisa_land = {
        'call_key': 'OBS',
        'master_path': '.',
        'path_structure': '{}/{{sta}}/{{year}}.{{jday}}/{{net}}.{{sta}}..{{cha}}.{{year}}.{{jday}}.mseed'.format(data_path),
        'sta_cha': ['HHZ', 'HHE', 'HHN'],
        'network': 'PM',
        'location': '',
        'years': [2021, 2022],
        'instrument_correction': True,
        'response_seismometer': '{}/RESP/{{net}}.{{sta}}.{{loc}}.{{cha}}.RESP'.format(data_path),
    }
    return {'civisa_land': civisa_land}

STATION_CODES_PATHS = {station_code: 'civisa_land' for station_code in ['ADH', 'BART', 'HOR', 'PAGU', 'PDA', 'PGRA', 'PICO', 'PSET', 'PSMN', 'ROSA', 'SRBC']}

def create_indo_data_format(data_path):
    land = {
        'call_key': 'OBS',
        'master_path': '.',
        'path_structure': '{}/{{sta}}/{{year}}.{{jday}}/{{net}}.{{sta}}..{{cha}}.{{year}}.{{jday}}.mseed'.format(data_path),
        'sta_cha': ['BHZ', 'BHE', 'BHN'],
        'network': 'PM',
        'location': '',
        'years': [2024],
        'instrument_correction': True,
        'response_seismometer': '{}/RESP/{{net}}.{{sta}}.{{loc}}.{{cha}}.RESP'.format(data_path),
    }
    return {'land': land}

INDO_DATA_FORMAT = {'AU_1': {'call_key': 'AU_1',
          'instrument_correction': True,
          'location': '',
          'master_path': '/data/alex/indo_pacific',
          'network': 'AU',
          'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
          'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
          'sta_cha': ['BH1', 'BH2', 'BHZ'],
          'years': [2024]},
 'AU_E_00': {'call_key': 'AU_E_00',
             'instrument_correction': True,
             'location': '00',
             'master_path': '/data/alex/indo_pacific',
             'network': 'AU',
             'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
             'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
             'sta_cha': ['BHE', 'BHN', 'BHZ'],
             'years': [2024]},
 'GE_1_00': {'call_key': 'GE_1_00',
             'instrument_correction': True,
             'location': '00',
             'master_path': '/data/alex/indo_pacific',
             'network': 'GE',
             'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
             'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
             'sta_cha': ['BH1', 'BH2', 'BHZ'],
             'years': [2024]},
 'GE_E': {'call_key': 'GE_E',
          'instrument_correction': True,
          'location': '',
          'master_path': '/data/alex/indo_pacific',
          'network': 'GE',
          'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
          'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
          'sta_cha': ['BHE', 'BHN', 'BHZ'],
          'years': [2024]},
 'G_E_00': {'call_key': 'G_E_00',
            'instrument_correction': True,
            'location': '00',
            'master_path': '/data/alex/indo_pacific',
            'network': 'G',
            'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
            'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
            'sta_cha': ['BHE', 'BHN', 'BHZ'],
            'years': [2024]},
 'HK_E': {'call_key': 'HK_E',
          'instrument_correction': True,
          'location': '',
          'master_path': '/data/alex/indo_pacific',
          'network': 'HK',
          'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
          'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
          'sta_cha': ['BHE', 'BHN', 'BHZ'],
          'years': [2024]},
 'IC_1_00': {'call_key': 'IC_1_00',
             'instrument_correction': True,
             'location': '00',
             'master_path': '/data/alex/indo_pacific',
             'network': 'IC',
             'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
             'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
             'sta_cha': ['BH1', 'BH2', 'BHZ'],
             'years': [2024]},
 'II_1_00': {'call_key': 'II_1_00',
             'instrument_correction': True,
             'location': '00',
             'master_path': '/data/alex/indo_pacific',
             'network': 'II',
             'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
             'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
             'sta_cha': ['BH1', 'BH2', 'BHZ'],
             'years': [2024]},
 'IU_1_00': {'call_key': 'IU_1_00',
             'instrument_correction': True,
             'location': '00',
             'master_path': '/data/alex/indo_pacific',
             'network': 'IU',
             'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
             'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
             'sta_cha': ['BH1', 'BH2', 'BHZ'],
             'years': [2024]},
 'JP_E': {'call_key': 'JP_E',
          'instrument_correction': True,
          'location': '',
          'master_path': '/data/alex/indo_pacific',
          'network': 'JP',
          'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
          'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
          'sta_cha': ['BHE', 'BHN', 'BHZ'],
          'years': [2024]},
 'MY_E': {'call_key': 'MY_E',
          'instrument_correction': True,
          'location': '',
          'master_path': '/data/alex/indo_pacific',
          'network': 'MY',
          'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
          'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
          'sta_cha': ['BHE', 'BHN', 'BHZ'],
          'years': [2024]},
 'PS_E': {'call_key': 'PS_E',
          'instrument_correction': True,
          'location': '',
          'master_path': '/data/alex/indo_pacific',
          'network': 'PS',
          'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
          'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
          'sta_cha': ['BHE', 'BHN', 'BHZ'],
          'years': [2024]},
 'PS_Z': {'call_key': 'PS_Z',
          'instrument_correction': True,
          'location': '',
          'master_path': '/data/alex/indo_pacific',
          'network': 'PS',
          'path_structure': '{}/{sta}/{year}.{jday}/{net}.{sta}.{loc}.{cha}.{year}.{jday}.mseed',
          'response_seismometer': '{}/RESP/{net}.{sta}.{loc}.{cha}.RESP',
          'sta_cha': ['BHZ'],
          'years': [2024]}}


STATION_CODES_PATHS_INDO= {'GSI': 'GE_E',
 'JOW': 'JP_E',
 'WRAB': 'II_1_00',
 'KAPI': 'II_1_00',
 'MTN': 'AU_E_00',
 'CHTO': 'IU_1_00',
 'INU': 'G_E_00',
 'MAJO': 'IU_1_00',
 'QIZ': 'IC_1_00',
#  'VIVO': 'PS_Z',
 'FITZ': 'AU_1',
 'JAGI': 'GE_E',
 'PMG': 'GE_1_00',
#  'SOEI': 'GE_E',
 'BKB': 'GE_E',
 'TATO': 'IU_1_00',
 'COCO': 'II_1_00',
#  'LUWI': 'GE_E',
 'PMBI': 'GE_E',
 'TNTI': 'GE_E',
 'MMRI': 'GE_E',
 'KKM': 'MY_E',
 'JAY': 'PS_E',
 'LHMI': 'GE_E',
 'FAKI': 'GE_E',
 'HKPS': 'HK_E',
 'SMRI': 'GE_E',
 'DAV': 'IU_1_00',
 'MNAI': 'GE_E'
 }